FROM node:12.14.0-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production
COPY . .
EXPOSE 3000

ENV DB ''
ENV DB_USER ''
ENV DB_PASS ''
ENV DB_SERVERS ''

ENV RABBIT_HOST ''
ENV RABBIT_PORT ''
ENV RABBIT_USER ''
ENV RABBIT_PASS ''

ENV SDP_URL 'http://localhost:8005'
ENV SDP_ACCESS_TOKEN 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY3VzdG9tZXItYmUiLCJpYXQiOjE2MTE2NTQwNjksImV4cCI6NDc2NzQxNDA2OX0.W9shWHCEeDVmM7ZKpNr6QvCBqsv0jSv8dHP1Yk9EBl0'
ENV DEST_LOCATION ''

ENV CUSTOMER_USER_URL 'http://localhost:8006'
ENV CUSTOMER_BACKEND_URL 'http://localhost:8007'
ENV CUSTOMER_USER_TOKEN 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2ktYmFja2VuZCIsImlhdCI6MTYyNTIwMTUwNiwiZXhwIjo0NzgwOTYxNTA2fQ.EWAibq87KjWRal4NdE9DEMpp9Po5yjUtqwdvSY0yJD4'

ENV REDIS_CLUSTER_NAME ''
ENV REDIS_CLUSTER_PASSWORD ''

ENV BASE_UPLOAD 'http://localhost:5003'
CMD [ "npm", "start"]
